---
- hosts: ambari
  roles:
    - { name: ranger_security, when: install_ranger == 'true' }
    - { name: oozie_security, when: install_oozie == 'true' }
    - { name: knox_security, when: install_knox == 'true' }
  run_once: true